version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'monday'
      time: '10:00'
    reviewers:
      - "mitchfen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: 'weekly'
      timezone: 'America/Detroit'
      day: 'monday'
      time: '10:00'
    reviewers:
      - "mitchfen"
