name: Publish container

on:
  push:
    branches:
      - "main"

# Set permissions of GITHUB_TOKEN for dependabot
permissions:
  contents: write
  pull-requests: write
  packages: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  publishContainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  cleanup:
    needs: publishContainer
    name: Cleanup untagged images
    runs-on: ubuntu-latest
    steps:
      - uses: mitchfen/cleanup-untagged-container-images@main
        with:
          username: 'mitchfen'
          container-name: 'highsec_ore_price_checker'
          token: ${{ secrets.GHCR_TOKEN }}
