name: Simple test

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Check Jita
        run: npm run check jita
