name: Simple test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update npm + install + build
        run: |
          sudo npm install -g npm@latest
          npm ci
          npm run build
