name: Simple test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  simpleTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update npm
        run: sudo npm install -g npm@latest

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
