name: simple-test

on: [push]

jobs:
  test-build-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build using tsc
        run: |
          npm build
          echo "BUILD SUCCESS"
